version: 1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - run: mvn clean test -DthreadCount=5
      - run:
          name: Generate report
          command: |
            mvn allure:report
      - store_test_results:
          path: ~/project/target/surefire-reports
      - store_artifacts:
          path: ~/project/target/site/allure-maven-plugin